### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by RomkeVdMeulen** [heruan/inject-properties#2]
Thanks for publishing this. I was following this over at [dependency-injection](https://github.com/aurelia/dependency-injection), also hoping to get a bit closer to CDI in my frontend code. I'm trying this out now, and it seems to be working very well. I'll let you know if I run into anything unexpected.

**Comment by heruan** [comment]
Thank you @RomkeVdMeulen. I'm currently writing an article to explain the details of interaction with Aurelia's core CDI and the implementation of this plugin, which I intend to extend with other features—I'll create issues and milestones to keep track on them soon!
